In [3]:
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\rajat.chauhan\Downloads\Data science\Waste Water Treatment Plant\data\processed\processed.csv")
df

Temp_C    pH  TSS_in_mg_l  BOD_in_mg_l  COD_in_mg_l  TSS_out_mg_l  \
0        24  8.75          219          145          268             9   
1        26  8.64          237          190          220            13   
2        25  8.73          227          140          288            11   
3        26  8.77          227          215          228            10   
4        27  8.60          290          165          244            12   
..      ...   ...          ...          ...          ...           ...   
335      19  7.21          292          130          292            26   
336      20  7.09          282          175          240            29   
337      20  7.20          272          140          288            27   
338      24  7.08          266          170          252            25   
339      23  7.06          295          160          288            29   

     BOD_out_mg_l  COD_out_mg_l  DO_out_mg_l  
0               5            48          5.1  
1               9            32          5.0  
2               6            44          5.3  
3              10            28          5.2  
4               9            36          5.4  
..            ...           ...          ...  
335            24            56          4.9  
336            29            44          4.7  
337            22            32          5.0  
338            29            56          5.0  
339            28            60          4.9  

[340 rows x 9 columns]

In [5]:
X = df.drop(columns="TSS_out_mg_l")
X

Temp_C    pH  TSS_in_mg_l  BOD_in_mg_l  COD_in_mg_l  BOD_out_mg_l  \
0        24  8.75          219          145          268             5   
1        26  8.64          237          190          220             9   
2        25  8.73          227          140          288             6   
3        26  8.77          227          215          228            10   
4        27  8.60          290          165          244             9   
..      ...   ...          ...          ...          ...           ...   
335      19  7.21          292          130          292            24   
336      20  7.09          282          175          240            29   
337      20  7.20          272          140          288            22   
338      24  7.08          266          170          252            29   
339      23  7.06          295          160          288            28   

     COD_out_mg_l  DO_out_mg_l  
0              48          5.1  
1              32          5.0  
2              44          5.3  
3              28          5.2  
4              36          5.4  
..            ...          ...  
335            56          4.9  
336            44          4.7  
337            32          5.0  
338            56          5.0  
339            60          4.9  

[340 rows x 8 columns]

In [6]:
y = df["TSS_out_mg_l"]
y

0       9
1      13
2      11
3      10
4      12
       ..
335    26
336    29
337    27
338    25
339    29
Name: TSS_out_mg_l, Length: 340, dtype: int64

In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, r2_score


# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train

Temp_C    pH  TSS_in_mg_l  BOD_in_mg_l  COD_in_mg_l  BOD_out_mg_l  \
66       27  8.14          242          165          296             5   
114      28  8.22          218          185          268            14   
7        27  8.67          273          130          208             8   
137      25  8.18          243          140          212            10   
328      17  7.21          294          145          264            28   
..      ...   ...          ...          ...          ...           ...   
188      22  8.13          244          135          272            22   
71       27  8.12          227          135          268             7   
106      26  8.18          213          125          244             9   
270       9  7.48          296          130          296            28   
102      25  8.48          248          170          300            10   

     COD_out_mg_l  DO_out_mg_l  
66             36          5.2  
114            32          5.0  
7              32          5.4  
137            40          4.9  
328            52          5.2  
..            ...          ...  
188            40          4.7  
71             48          5.6  
106            28          5.0  
270            40          5.0  
102            52          5.3  

[272 rows x 8 columns]

## Checking multicollinearity

In [12]:
X.corr()

Temp_C        pH  TSS_in_mg_l  BOD_in_mg_l  COD_in_mg_l  \
Temp_C        1.000000  0.405651    -0.717107    -0.095327    -0.167265   
pH            0.405651  1.000000    -0.368828     0.021819    -0.066195   
TSS_in_mg_l  -0.717107 -0.368828     1.000000     0.052816     0.174765   
BOD_in_mg_l  -0.095327  0.021819     0.052816     1.000000     0.250673   
COD_in_mg_l  -0.167265 -0.066195     0.174765     0.250673     1.000000   
BOD_out_mg_l -0.802162 -0.476977     0.728666     0.121966     0.226356   
COD_out_mg_l -0.259591 -0.093543     0.270173    -0.017608     0.146389   
DO_out_mg_l   0.539039  0.354109    -0.514207     0.031915    -0.087948   

              BOD_out_mg_l  COD_out_mg_l  DO_out_mg_l  
Temp_C           -0.802162     -0.259591     0.539039  
pH               -0.476977     -0.093543     0.354109  
TSS_in_mg_l       0.728666      0.270173    -0.514207  
BOD_in_mg_l       0.121966     -0.017608     0.031915  
COD_in_mg_l       0.226356      0.146389    -0.087948  
BOD_out_mg_l      1.000000      0.374132    -0.581825  
COD_out_mg_l      0.374132      1.000000    -0.205639  
DO_out_mg_l      -0.581825     -0.205639     1.000000

Split the Data:

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


Fit the Scaler on the Training Data:

In [14]:
from sklearn.preprocessing import MinMaxScaler

scaler_X = MinMaxScaler()
X_train_scaled = scaler_X.fit_transform(X_train)
X_train_scaled


array([[0.9047619 , 0.61714286, 0.54545455, ..., 0.        , 0.25      ,
        0.63636364],
       [0.95238095, 0.66285714, 0.36363636, ..., 0.375     , 0.16666667,
        0.45454545],
       [0.9047619 , 0.92      , 0.78030303, ..., 0.125     , 0.16666667,
        0.81818182],
       ...,
       [0.85714286, 0.64      , 0.32575758, ..., 0.16666667, 0.08333333,
        0.45454545],
       [0.04761905, 0.24      , 0.95454545, ..., 0.95833333, 0.33333333,
        0.45454545],
       [0.80952381, 0.81142857, 0.59090909, ..., 0.20833333, 0.58333333,
        0.72727273]])

In [17]:
len(X_train_scaled)

272

Transform the Test Data:

In [15]:
X_test_scaled = scaler_X.transform(X_test)
X_test_scaled

array([[0.04761905, 0.54285714, 0.92424242, 0.68181818, 0.67857143,
        0.95833333, 0.66666667, 0.27272727],
       [0.9047619 , 0.20571429, 0.33333333, 0.59090909, 0.75      ,
        0.45833333, 0.5       , 0.63636364],
       [0.85714286, 0.33142857, 0.59090909, 0.45454545, 0.78571429,
        0.33333333, 0.08333333, 0.36363636],
       [0.71428571, 0.92571429, 0.46969697, 0.72727273, 0.60714286,
        0.45833333, 0.58333333, 0.54545455],
       [0.9047619 , 0.56      , 0.77272727, 0.31818182, 1.        ,
        0.20833333, 0.5       , 0.18181818],
       [0.23809524, 0.32      , 0.95454545, 0.        , 0.78571429,
        0.75      , 0.66666667, 0.18181818],
       [0.71428571, 0.27428571, 0.74242424, 0.68181818, 0.75      ,
        0.66666667, 0.83333333, 0.45454545],
       [0.04761905, 0.10285714, 0.81818182, 0.54545455, 0.96428571,
        0.625     , 0.33333333, 0.27272727],
       [0.57142857, 0.08      , 0.77272727, 0.36363636, 0.78571429,
        0.70833333, 0.166666

In [16]:
len(X_test_scaled)

68

(Optional) Scale the Output if Necessary:

If you're scaling the output for a regression problem, fit the scaler on y_train and then transform both y_train and y_test.

In [18]:
# Assuming y_train is a Pandas Series
scaler_y = MinMaxScaler()

# Convert y_train to a NumPy array and then reshape
y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1))

# Similarly, transform y_test
y_test_scaled = scaler_y.transform(y_test.values.reshape(-1, 1))
y_test_scaled

array([[0.69565217],
       [0.04347826],
       [0.30434783],
       [0.04347826],
       [0.30434783],
       [0.60869565],
       [0.65217391],
       [0.95652174],
       [0.82608696],
       [0.17391304],
       [0.2173913 ],
       [0.60869565],
       [1.13043478],
       [0.26086957],
       [0.08695652],
       [0.60869565],
       [0.43478261],
       [0.56521739],
       [0.7826087 ],
       [0.08695652],
       [0.86956522],
       [0.04347826],
       [0.34782609],
       [0.08695652],
       [0.26086957],
       [0.17391304],
       [0.13043478],
       [0.69565217],
       [0.2173913 ],
       [0.82608696],
       [0.56521739],
       [0.04347826],
       [0.17391304],
       [0.60869565],
       [0.2173913 ],
       [0.04347826],
       [0.65217391],
       [0.86956522],
       [0.26086957],
       [0.08695652],
       [0.34782609],
       [0.08695652],
       [0.13043478],
       [0.65217391],
       [0.04347826],
       [0.69565217],
       [0.73913043],
       [0.782

scaler_X and scaler_y are the trained on the input and output data correctly now

1. Linear Regression
Overview: Linear Regression is one of the simplest and most interpretable regression models. It assumes a linear relationship between the input features and the target variable.

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Initialize the model
model = LinearRegression()

# Train the model
model.fit(X_train_scaled, y_train_scaled)

# Make predictions
y_pred = model.predict(X_test_scaled)

# Evaluate the model
mse = mean_squared_error(y_test_scaled, y_pred)
r2 = r2_score(y_test_scaled, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R^2 Score: {r2}')

Mean Squared Error: 0.015984648184832865
R^2 Score: 0.8042759760609551


2. Random Forest Regressor
Overview: Random Forest is an ensemble learning method that builds multiple decision trees and merges them together to get a more accurate and stable prediction.

In [20]:
from sklearn.ensemble import RandomForestRegressor

# Initialize the model
model = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model
model.fit(X_train_scaled, y_train_scaled.ravel())  # ravel() is used to flatten the target array

# Make predictions
y_pred = model.predict(X_test_scaled)

# Evaluate the model
mse = mean_squared_error(y_test_scaled, y_pred)
r2 = r2_score(y_test_scaled, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R^2 Score: {r2}')


Mean Squared Error: 0.012688243633937503
R^2 Score: 0.8446388014276347


3. Support Vector Regressor (SVR)
Overview: SVR uses the principles of Support Vector Machines but for regression tasks. It tries to fit the best line within a specified margin, ignoring errors as long as they are within that margin.

In [21]:
from sklearn.svm import SVR

# Initialize the model
model = SVR(kernel='rbf')  # 'rbf' kernel is commonly used for regression

# Train the model
model.fit(X_train_scaled, y_train_scaled.ravel())

# Make predictions
y_pred = model.predict(X_test_scaled)

# Evaluate the model
mse = mean_squared_error(y_test_scaled, y_pred)
r2 = r2_score(y_test_scaled, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R^2 Score: {r2}')

Mean Squared Error: 0.014954012094270108
R^2 Score: 0.8168955996228395


4. Gradient Boosting Regressor
Overview: Gradient Boosting is another ensemble technique that builds models sequentially, each one correcting the errors of its predecessor. It often yields better performance than Random Forest.

In [22]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Initialize the model
model = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, random_state=42)

# Train the model
model.fit(X_train_scaled, y_train_scaled.ravel())

# Make predictions
y_pred = model.predict(X_test_scaled)

# Evaluate the model
mse = mean_squared_error(y_test_scaled, y_pred)
r2 = r2_score(y_test_scaled, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R^2 Score: {r2}")


Mean Squared Error: 0.012527418484214924
R^2 Score: 0.8466080249657648


5. Decision Tree Regressor

In [23]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Initialize the model
decision_tree_model = DecisionTreeRegressor(random_state=42)

# Train the model
decision_tree_model.fit(X_train_scaled, y_train_scaled.ravel())

# Make predictions
y_pred_dt = decision_tree_model.predict(X_test_scaled)

# Evaluate the model
mse_dt = mean_squared_error(y_test_scaled, y_pred_dt)
r2_dt = r2_score(y_test_scaled, y_pred_dt)

print(f"Decision Tree Mean Squared Error: {mse_dt}")
print(f"Decision Tree R^2 Score: {r2_dt}")


Decision Tree Mean Squared Error: 0.024936061381074168
Decision Tree R^2 Score: 0.694670397605258


6. Baseline Model or Mean Baseline Model. This model simply predicts the mean value of the target variable for all inputs. It serves as a benchmark to compare more complex models.

In [24]:
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score

# Calculate the mean of the training target values
y_mean = np.mean(y_train_scaled)

# Predict the mean for all test samples
y_pred_baseline = np.full_like(y_test_scaled, y_mean)

# Evaluate the baseline model
mse_baseline = mean_squared_error(y_test_scaled, y_pred_baseline)
r2_baseline = r2_score(y_test_scaled, y_pred_baseline)

print(f"Baseline Mean Squared Error: {mse_baseline}")
print(f"Baseline R^2 Score: {r2_baseline}")


Baseline Mean Squared Error: 0.08258202560324696
Baseline R^2 Score: -0.011175608571814655
